# docker-compose.yml
services:
  app:
    build: .
    container_name: app
    # Наследуем CMD из Dockerfile, поэтому command не нужен
    # command: sh /app/init_db.sh
    volumes:
      - .:/app          # смонтирует весь проект, но файл уже в образе
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
